
version: 2

models:

  - name: business_model
    description: "Information needed for business model"        
    columns:
      - name: business_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: price_range
        description: "Given as a value between 1 and 4, with 1 being the least expensive, and 4 being the most expensive"    