dbt_yelp:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('YELP_DB_HOST') }}"
      username: "{{ env_var('YELP_DB_USER') }}"
      password: "{{ env_var('YELP_DB_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('YELP_DB_NAME') }}"
      schema: "{{ env_var('YELP_DB_SCHEMA') }}"
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds